name: flutter_ui_kit_example
description: "Living catalog demo for flutter_ui_kit package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_ui_kit:
    path: ../
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  heroicons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
