name: Deploy Web Example to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Diperlukan untuk push ke branch gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.x' # Sesuai dengan sdk environment di pubspec.yaml

      - name: Install dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Build Web
        working-directory: ./example
        run: flutter build web --base-href "/flutter_ui_kit/" --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
